# Generated by Django 5.2.5 on 2026-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_caption_tag_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
